---
- name: Configure RHEL Servers
  hosts: rhel_servers #your target machine ip or name
  become: true
  tasks:
    - name: Ensure Apache is installed
      yum:
        name: httpd
        state: present

    - name: Copy Apache configuration file
      copy:
        src: files/httpd.conf
        dest: /etc/httpd/conf/httpd.conf
        owner: root
        group: root
        mode: '0644'

    - name: Start Apache service
      service:
        name: httpd
        state: started
        enabled: true
